const CARDS=['amethyst-heart','celestial-potion','crystal-ball','fuchsia-ribbon','golden-paw','indigo-bowtie','jeweled-key','mistic-yarn','rose-pufferfish','royal-cat-bed','sapphire-paw','silver-bag','starry-mic','turquoise-cushion'];
const CP='asset/cards/',SM=7,CS=62;
let stage=1,tiles=[],slots=[],hist=[],undo=2,shuf=1,score=0,on=false;
function sh(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=0|Math.random()*(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
function build(cnt){const bd=document.getElementById('game-board');const bw=bd.offsetWidth||360,bh=bd.offsetHeight||460;tiles=[];const chosen=sh(CARDS).slice(0,Math.ceil(cnt/3)*3);const pool=[];chosen.forEach(c=>{for(let i=0;i<3;i++)pool.push(c);});sh(pool).slice(0,cnt).forEach((card,i)=>{const px=50+Math.random()*(bw-CS-100),py=30+Math.random()*(bh-CS-60);tiles.push({id:i,card,px,py,layer:0,rm:false});});}
function isBlocked(t){const thresh=CS*0.15;for(const o of tiles){if(o.rm||o.id===t.id)continue;const ox=Math.min(t.px+CS,o.px+CS)-Math.max(t.px,o.px);const oy=Math.min(t.py+CS,o.py+CS)-Math.max(t.py,o.py);if(ox>=thresh&&oy>=thresh)return true;}return false;}
function render(){const bd=document.getElementById('game-board');bd.innerHTML='';tiles.filter(t=>!t.rm).forEach(t=>{const bl=isBlocked(t);const el=document.createElement('div');el.style.cssText=`position:absolute;left:${t.px}px;top:${t.py}px;width:${CS}px;height:${CS}px;border:${bl?'1.5px solid #555':'2.5px solid gold'};border-radius:4px;filter:brightness(${bl?.5:1});cursor:${bl?'not-allowed':'pointer'};pointer-events:${bl?'none':'auto'};background:rgba(20,10,35,.3)`;const img=document.createElement('img');img.src=CP+t.card+'.png';img.style.cssText='width:100%;height:100%;object-fit:cover';el.appendChild(img);if(!bl)el.onclick=()=>clickTile(t);bd.appendChild(el);});renderSlots();renderUI();}
function renderSlots(){const bar=document.getElementById('slot-bar');bar.innerHTML='';for(let i=0;i<SM;i++){const d=document.createElement('div');d.style.cssText=`width:40px;height:40px;border:2px dashed ${slots[i]?'gold':'#666'};border-radius:3px;display:flex;align-items:center;justify-content:center;background:rgba(30,15,50,.4)`;if(slots[i]){const m=document.createElement('img');m.src=CP+slots[i]+'.png';m.style.cssText='width:34px;height:34px;object-fit:cover';d.appendChild(m);}bar.appendChild(d);}document.getElementById('slot-count').textContent=slots.length+'/'+SM;}
function renderUI(){document.getElementById('score').textContent='★ '+score.toLocaleString();if(!tiles.filter(t=>!t.rm).length&&!slots.length)win();}
function insertSlot(card){slots.push(card);}
function checkMatch(){let m={};slots.forEach((c,i)=>{(m[c]=m[c]||[]).push(i);});for(const[,idx] of Object.entries(m)){if(idx.length>=3){slots=slots.filter((_,i)=>!idx.slice(0,3).includes(i));score+=300;return true;}}return false;}
function clickTile(t){if(!on||t.rm||isBlocked(t))return;hist.push(tiles.map(x=>({id:x.id,rm:x.rm})));t.rm=true;insertSlot(t.card);while(checkMatch());render();if(slots.length>=SM){on=false;showResult(false);}}
function doUndo(){if(!on||!undo||!hist.length)return;const s=hist.pop();s.forEach(ts=>{const t=tiles.find(x=>x.id===ts.id);if(t)t.rm=ts.rm;});slots.pop();undo--;document.getElementById('undo-badge').textContent=undo;render();}
function doShuffle(){if(!on||!shuf)return;shuf--;document.getElementById('shuf-badge').textContent=shuf;const a=tiles.filter(t=>!t.rm),c=sh(a.map(t=>t.card));a.forEach((t,i)=>t.card=c[i]);render();}
function doWithdraw(){}
function showResult(isWin){const ov=document.getElementById('overlay');ov.style.display='flex';ov.innerHTML=`<div class="result-box ${isWin?'win':'lose'}"><h2>${isWin?'🎉 PERFECT!':'😿 TOO BAD'}</h2><p>${isWin?'Score: '+score.toLocaleString():'Slots are full!'}</p><button onclick="restartGame()">${isWin?'Play Again':'Try Again'}</button><button onclick="window.location.href='index.html'">Home</button></div>`;}
function win(){on=false;showResult(true);}
function restartGame(){document.getElementById('overlay').style.display='none';stage=1;tiles=[];slots=[];hist=[];undo=2;shuf=1;score=0;on=true;document.getElementById('undo-badge').textContent=2;document.getElementById('shuf-badge').textContent=1;build(12);render();}
window.addEventListener('load',()=>{on=true;build(12);render();});
window.doUndo=doUndo;window.doShuffle=doShuffle;window.doWithdraw=doWithdraw;window.restart=restartGame;
